springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

logging:
  level:
    com.example.backend: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update